create type public.edge_type as enum ('reply', 'author', 'prompt');

CREATE TABLE IF NOT EXISTS nodes
(
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone,
    content text not null,
    avatar_url text,
    avatar_label text,
    attributes jsonb default '{}'::jsonb not null
);

CREATE TABLE IF NOT EXISTS edges
(
    from_id bigint references nodes on delete cascade,
    to_id bigint references nodes on delete cascade,
    type edge_type not null,
    primary key (from_id, to_id)
);

CREATE INDEX IF NOT EXISTS edges_to_id_from_id_idx ON edges (to_id, from_id);

alter table nodes
  enable row level security;

create policy "Nodes are viewable by everyone." on nodes
  for select using (true);

-- create view tweets as

-- alter view tweets_full owner to authenticated;
