-- Create a table for fictional profiles
create table fprofiles
(
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    username text unique not null,
    full_name text not null,
    avatar_url text,

    constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS)
-- See https://supabase.com/docs/guides/auth/row-level-security for more details.
alter table fprofiles
  enable row level security;

create policy "Fictional profiles are viewable by everyone." on fprofiles
  for select using (true);

-- Set up Storage!
insert into storage.buckets (id, name)
  values ('favatars', 'favatars');

-- Set up access controls for storage.
-- See https://supabase.com/docs/guides/storage#policy-examples for more details.
create policy "Fictional avatar images are publicly accessible." on storage.objects
  for select using (bucket_id = 'favatars');

comment on table public.fprofiles
    IS 'Fictional profiles which can author tweets.';
